runtime: custom
env: flex
entrypoint: gunicorn3 -b :$PORT main:app

runtime_config:
  python_version: 3


env_variables:
    PUBSUB_TOPIC: hyper-beam
    PUBSUB_VERIFICATION_TOKEN: abc
    GOOGLE_CLOUD_PROJECT: hyper-beam 
    CLOUD_STORAGE_BUCKET: hyper-beam.appspot.com  
    FIREBASE_PROJECT_ID: 'hyper-beam' 
    GOOGLE_APPLICATION_CREDENTIALS: "pdf_highlights/hyper-beam-firebase-adminsdk-3t5wg-60d7f00668.json"

  # handlers:
  #   - url: .*
  #     script: main.app
    
    

# Change based on testing requirements
resources:
    cpu: 2
    memory_gb: 4.0
    disk_size_gb: 20

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 20
    cool_down_period_sec: 120
    cpu_utilization:
      target_utilization: 0.7

    